name: Release with STL

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install OpenSCAD
      run: sudo apt-get install openscad && openscad --version
    - name: Build
      run: make -j2
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: New Release
        files: '*.stl'
        generate_release_notes: true
