name: Update Media

on:
  workflow_dispatch: 
    inputs:
      message:
        description: 'Commit message'
        default: 'Update media'
        required: true
      stls:
        description: 'STLs'
        type: boolean
        default: true
        required: true
      icons:
        description: 'Icons'
        type: boolean
        default: true
        required: true
      images:
        description: 'Images'
        type: boolean
        default: false
        required: true
      dryrun:
        description: 'Dry-run'
        type: boolean
        default: false
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install OpenSCAD
      run: |
        sudo apt-get -qq install openscad xvfb && openscad --version
    - name: Build
      run: |
        TARGETS=""
        if [ '${{github.event.inputs.stls}}' = 'true' ]; then
          TARGETS="all $TARGETS"
        fi
        if [ '${{github.event.inputs.images}}' = 'true' ]; then
          TARGETS="images $TARGETS"
        fi
        if [ '${{github.event.inputs.icons}}' = 'true' ]; then
          TARGETS="icons $TARGETS"
        fi
        if [ ! -z "$TARGETS" ]; then
          xvfb-run -e /dev/stdout make -j2 $TARGETS
        fi
    - name: Switch to Media Branch
      uses: actions/checkout@v2
      with:
        ref: media
        clean: false
    - name: Checkin Media
      run : |
        git clean -ffdx -e '*.stl' -e '*.png'
        if [ '${{github.event.inputs.images}}' = 'true' ] || [ '${{github.event.inputs.icons}}' = 'true' ]; then
          mv *.png media/
        fi
        if [ '${{github.event.inputs.stls}}' = 'true' ]; then
          mv *.stl media/
        fi
        git status --short
        if [ -z "$(git status --porcelain)" ]; then 
          # Working directory clean
          echo "Media files are up to date"
        else 
          # Uncommitted changes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add media/*.stl media/*.png
          git commit -m '${{ github.event.inputs.message }}'
          if [ '${{ github.event.inputs.dryrun}}' = 'true' ]; then
            git push --dry-run origin media:media
            echo "Media files would have been updated (dry-run)"
          else
            git push origin media:media
            echo "Media files updated"
          fi
        fi
